---
- name: Deny incoming
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Deny incoming
  community.general.ufw:
    default: deny
    direction: routed

- name: Allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Enable ufw
  community.general.ufw:
    state: enabled
